version: "3.7"

services:
  php:
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: .docker/php
      dockerfile: Dockerfile
    user: www-data
    volumes:
      - ./dist:/var/www/html
      - ./pages:/workspace
    ports:
      - "4000:80"
